### ISSUE TITLE
HyRAM build folder missing python folder

### ISSUE THREAD

**Issue by spfeiffer1** [sandialabs/hyram#1]
I was following your setup and build instructions from B.1. to B.4.6.
Following step B.4.6., when I ran Build on the Installer in the Solution Explorer, I got the following:
Note: **2>  "skipping python copy".**

1>------ Build started: Project: DefaultParsing, Configuration: Debug Any CPU ------
2>------ Build started: Project: PythonDir, Configuration: Debug Any CPU ------
1>  DefaultParsing -> C:\build\bin\Debug\DefaultParsing.dll
3>------ Build started: Project: JrString, Configuration: Debug Any CPU ------
4>------ Build started: Project: JrConversions, Configuration: Debug Any CPU ------
3>  JrString -> C:\build\bin\Debug\JtString.dll
5>------ Build started: Project: JrCollections, Configuration: Debug Any CPU ------
5>  JrCollections -> C:\build\bin\Debug\JrCollections.dll
6>------ Build started: Project: UIHelpers, Configuration: Debug Any CPU ------
2>  PythonDir -> C:\build\bin\Debug\PythonDir.dll
**2>  "skipping python copy".**
2>  C:\hyram\App\PythonDir\\..\..\python_contributions\hyram\hyram\qra_setup.py
2>  C:\hyram\App\PythonDir\\..\..\python_contributions\hyram\hyram\__init__.py

And the following Error message after the above message:
------ Starting pre-build validation for project 'HyRAMSetup' ------ 
ERROR: Unable to find source file 'C:\build\bin\Release\python\Lib\site-packages\numpy\core\_methods.py' for file '_methods.py', located in '[TARGETDIR]\python\Lib\site-packages\numpy\core', the file may be absent or locked.
ERROR: Unable to find source file 'C:\build\bin\Release\python\Lib\site-packages\networkx\linalg\tests\__pycache__\test_spectrum.cpython-36.pyc' for file 'test_spectrum.cpython-36.pyc', located in '[TARGETDIR]\python\Lib\site-packages\networkx\linalg\tests\__pycache__', the file may be absent or locked.
ERROR: Unable to find source file 'C:\build\bin\Release\python\Lib\idlelib\__pycache__\search.cpython-36.pyc' for file 'search.cpython-36.pyc', located in '[TARGETDIR]\python\Lib\idlelib\__pycache__', the file may be absent or locked.
ERROR: Unable to find source file 'C:\build\bin\Release\python\Lib\site-packages\dill\tests\__main__.py' for file '__main__.py', located in '[TARGETDIR]\python\Lib\site-packages\dill\tests', the file may be absent or locked.
ERROR: Unable to find source file 'C:\build\bin\Release\python\Lib\site-packages\pandas\tests\indexes\timedeltas\__init__.py' for file '__init__.py', located in '[TARGETDIR]\python\Lib\site-packages\pandas\tests\indexes\timedeltas', the file may be absent or locked.
....
.....
.....
------ Pre-build validation for project 'HyRAMSetup' completed ------
10>------ Build started: Project: HyRAMSetup, Configuration: Debug ------
========== Build: 9 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Then when I click "Start", I get the following error message at this location:
// Cianan: Must initialize once instead of during each use to avoid re-import issues
            PythonEngine.Initialize()
Error message:
System.DllNotFoundException: 'Unable to load DLL 'python36': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

Upon checking, the build directory (\build\bin\Debug\) was missing the "python" which should contain the python36 DLL files. 
It looks like I have to manually copy the python folder from the \hyram\App\PythonDir folder to the \build\bin\Debug\, it worked.

**Comment by ghost** [comment]
The new updated version 3.0 and the updated instructions in the README and CONTRIBUTING should address this issue
