### ISSUE TITLE
very high leak frequency parameters for ch4 liquid joint

### ISSUE THREAD

**Issue by mortendahlby** [sandialabs/hyram#5]
Ref. the values for ch4 liquid joint found here, which are very high:
https://github.com/sandialabs/hyram/blob/master/src/hyram/hyram/qra/data/component_data.py

The parameters for CH4 hose liquid also seem strange since they give increasing frequencies for larger hole sies. 

    'joint': [
        [10.4669, 2.1960],
        [6.1666, 1.6594],
        [1.8652, 1.1464],
        [-2.4345, 0.7068],
        [-6.7363, 0.6198],
    ],

**Comment by ghost** [comment]
The values for the methane leak frequencies were developed in this report: https://doi.org/10.2172/1782412

That report also discussed the hose values, which do give increasing frequencies for larger hole sizes. 

We would be very interested to hear about other potential leak frequency sources of data that weren't considered in that report!

**Comment by mortendahlby** [comment]
Ok, thanks, I see these are discussed as uncertainties in the report. >35 000 leaks per joint per year is very high, I guess this is not supported by your data, but rather a modelling artifact?

**Comment by ghost** [comment]
I would say that the leak frequencies are supported by the data available, but there is not very much data available for joints, especially for the smaller leak sizes. Looking at Tables 4-1 and 4-3 in the report, there are only a handful of data points available for joints. Additionally, the data points that are available are for larger leaks only: Figure 5-4 shows the data available for leak areas of 0.1 and 1.0, and how that extrapolates down to very high leak frequencies for the smaller leak sizes.

I would also point out that a leak area of 0.01% is very small: on a pipe with an inner diameter of 1.5 inches, a 0.01% leak area would have a leak diameter of 0.015 inches. So depending on the system and the analysis, these very small leaks may not be a significant contributor to risk, even with potentially unrealistic leak frequencies. Of course, if they are, a risk analyst would need to evaluate what, if any, revisions to the leak frequencies seem justified.
